-- MySQL Script generated by MySQL Workbench
-- Mon Jun 12 10:45:56 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `idUser` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Username` VARCHAR(45) NOT NULL,
  `Firstname` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`),
  UNIQUE INDEX `UNIQUE_Email` (`Email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Baskets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Baskets` (
  `idBasket` INT NOT NULL,
  `Users_idUsers` INT NOT NULL,
  PRIMARY KEY (`idBasket`),
  INDEX `fk_Basket_Users1_idx` (`Users_idUsers` ASC) VISIBLE,
  CONSTRAINT `fk_Basket_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `mydb`.`Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Articles` (
  `idArticle` INT NOT NULL,
  `Brand` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(1000) NOT NULL,
  `Price` INT(11) NOT NULL,
  `Stock` INT(11) NOT NULL,
  `Image` BLOB(255) NOT NULL,
  `Imagepath` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idArticle`),
  UNIQUE INDEX `UNIQUE_Name` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Purchases` (
  `idPurchase` INT NOT NULL,
  `Date` DATE NOT NULL,
  `Total` INT(11) NOT NULL,
  `Users_idUsers` INT NOT NULL,
  PRIMARY KEY (`idPurchase`),
  INDEX `fk_Purchase_Users1_idx` (`Users_idUsers` ASC) VISIBLE,
  CONSTRAINT `fk_Purchase_Users1`
    FOREIGN KEY (`Users_idUsers`)
    REFERENCES `mydb`.`Users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Baskets_has_Articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Baskets_has_Articles` (
  `Baskets_idBasket` INT NOT NULL,
  `Articles_idArticle` INT NOT NULL,
  `Number` INT(1000) NOT NULL,
  PRIMARY KEY (`Baskets_idBasket`, `Articles_idArticle`),
  INDEX `fk_Baskets_has_Articles_Articles1_idx` (`Articles_idArticle` ASC) VISIBLE,
  INDEX `fk_Baskets_has_Articles_Baskets1_idx` (`Baskets_idBasket` ASC) VISIBLE,
  CONSTRAINT `fk_Baskets_has_Articles_Baskets1`
    FOREIGN KEY (`Baskets_idBasket`)
    REFERENCES `mydb`.`Baskets` (`idBasket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Baskets_has_Articles_Articles1`
    FOREIGN KEY (`Articles_idArticle`)
    REFERENCES `mydb`.`Articles` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Purchases_has_Articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Purchases_has_Articles` (
  `Purchases_idPurchase` INT NOT NULL,
  `Articles_idArticle` INT NOT NULL,
  PRIMARY KEY (`Purchases_idPurchase`, `Articles_idArticle`),
  INDEX `fk_Purchases_has_Articles_Articles1_idx` (`Articles_idArticle` ASC) VISIBLE,
  INDEX `fk_Purchases_has_Articles_Purchases1_idx` (`Purchases_idPurchase` ASC) VISIBLE,
  CONSTRAINT `fk_Purchases_has_Articles_Purchases1`
    FOREIGN KEY (`Purchases_idPurchase`)
    REFERENCES `mydb`.`Purchases` (`idPurchase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Purchases_has_Articles_Articles1`
    FOREIGN KEY (`Articles_idArticle`)
    REFERENCES `mydb`.`Articles` (`idArticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
